server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: order-services
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce_order
    username: postgres
    password: code_java
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true